apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource 
metadata:
  name: we-postgres         # Name of the resource
  labels:                         # Labels that will be applied to the resource
    app: we-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:                       # Selects any Pod with labels `app=polling-app,tier=mysql`
    app: we-postgres
    tier: postgres